server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  datasource:
    url: jdbc:mysql://192.168.101.72:3308/oauth_server?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 20
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          ##指定DDL mode (none, validate, update, create, create-drop)
          auto: update
          dialect: org.hibernate.dialect.MySQL5Dialect
          jdbc:
            batch_size: 500
            batch_version_data: true
            order_inserts: true
            order_updates: true









#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://yang2.com:9000
